// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface PlayoffTeamResult {
  team_name: string;
  reach_pct: Record<string, number>;
  outcome_pct: Record<string, number>;
}

export interface PlayoffSimulationMeta {
  num_trials: number;
  format: string;
  best_of: { grand_final: number; default: number };
  no_bracket_reset: boolean;
  ub_r1_pairings_forced: boolean;
  ub_r1_pairings: [number, number][];
  bracket_routing: Record<string, { best_of: number; winner_to: string | null; loser_to: string | null }>;
  match_order: string[];
  reach_pct_note: string;
  outcome_pct_note: string;
  slots_note: string;
}

export interface PlayoffSlotDistribution {
  a: Record<string, number>;
  b: Record<string, number>;
  winner: Record<string, number>;
}

export const playoffSimulationMeta: PlayoffSimulationMeta = {
  "num_trials": 1000000,
  "format": "double_elimination_8_team",
  "best_of": {
    "grand_final": 5,
    "default": 3
  },
  "no_bracket_reset": true,
  "ub_r1_pairings_forced": true,
  "ub_r1_pairings": [
    [
      10150413,
      7119388
    ],
    [
      9572001,
      8255888
    ],
    [
      2163,
      9823272
    ],
    [
      10136357,
      9247354
    ]
  ],
  "bracket_routing": {
    "ub_r1_1": {
      "best_of": 3,
      "winner_to": "ub_r2_1:a",
      "loser_to": "lb_r1_1:a"
    },
    "ub_r1_2": {
      "best_of": 3,
      "winner_to": "ub_r2_1:b",
      "loser_to": "lb_r1_1:b"
    },
    "ub_r1_3": {
      "best_of": 3,
      "winner_to": "ub_r2_2:a",
      "loser_to": "lb_r1_2:a"
    },
    "ub_r1_4": {
      "best_of": 3,
      "winner_to": "ub_r2_2:b",
      "loser_to": "lb_r1_2:b"
    },
    "ub_r2_1": {
      "best_of": 3,
      "winner_to": "ub_final:a",
      "loser_to": "lb_r2_2:a"
    },
    "ub_r2_2": {
      "best_of": 3,
      "winner_to": "ub_final:b",
      "loser_to": "lb_r2_1:a"
    },
    "lb_r1_1": {
      "best_of": 3,
      "winner_to": "lb_r2_1:b",
      "loser_to": null
    },
    "lb_r1_2": {
      "best_of": 3,
      "winner_to": "lb_r2_2:b",
      "loser_to": null
    },
    "ub_final": {
      "best_of": 3,
      "winner_to": "grand_final:a",
      "loser_to": "lb_final:b"
    },
    "lb_r2_1": {
      "best_of": 3,
      "winner_to": "lb_r3:a",
      "loser_to": null
    },
    "lb_r2_2": {
      "best_of": 3,
      "winner_to": "lb_r3:b",
      "loser_to": null
    },
    "lb_r3": {
      "best_of": 3,
      "winner_to": "lb_final:a",
      "loser_to": null
    },
    "lb_final": {
      "best_of": 3,
      "winner_to": "grand_final:b",
      "loser_to": null
    },
    "grand_final": {
      "best_of": 5,
      "winner_to": null,
      "loser_to": null
    }
  },
  "match_order": [
    "ub_r1_1",
    "ub_r1_2",
    "ub_r1_3",
    "ub_r1_4",
    "ub_r2_1",
    "ub_r2_2",
    "lb_r1_1",
    "lb_r1_2",
    "ub_final",
    "lb_r2_1",
    "lb_r2_2",
    "lb_r3",
    "lb_final",
    "grand_final"
  ],
  "reach_pct_note": "Probability of being alive entering / winning each named stage. ub_r1_win/ub_r2_win/ub_final_win are P(won that specific upper-bracket match); ub_final_reach/lb_final_reach/grand_final_reach are P(played in that match, win or lose); champion is P(won the Grand Final).",
  "outcome_pct_note": "Probability of being eliminated at each specific stage (mutually exclusive, sums to ~100% per team). A team is never 'eliminated' by an upper-bracket loss - it drops to the corresponding lower-bracket match and keeps playing, so the earliest possible elimination is eliminated_lb_r1.",
  "slots_note": "For the bracket-diagram UI: per match_id, 'a'/'b' are the probability distribution (percent, sorted descending) of which team ends up occupying that slot - a delta at 100% for the 4 known UB R1 matches, genuinely spread out for everything downstream. 'winner' is the probability distribution of which team wins that specific match. Zero-probability teams are omitted (not every team can reach every slot)."
};

export const playoffSimulation: Record<string, PlayoffTeamResult> = {
  "2163": {
    "team_name": "Team Liquid",
    "reach_pct": {
      "ub_r1_win": 46.99,
      "ub_r2_win": 24.79,
      "ub_final_reach": 24.79,
      "ub_final_win": 11.24,
      "lb_final_reach": 26.96,
      "grand_final_reach": 24.23,
      "champion": 10.65
    },
    "outcome_pct": {
      "eliminated_lb_r1": 19.77,
      "eliminated_lb_r2": 27.89,
      "eliminated_lb_r3": 14.14,
      "eliminated_lb_final": 13.97,
      "runner_up": 13.58,
      "champion": 10.65
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "reach_pct": {
      "ub_r1_win": 54.49,
      "ub_r2_win": 21.75,
      "ub_final_reach": 21.75,
      "ub_final_win": 10.39,
      "lb_final_reach": 24.44,
      "grand_final_reach": 21.33,
      "champion": 9.28
    },
    "outcome_pct": {
      "eliminated_lb_r1": 24.8,
      "eliminated_lb_r2": 26.39,
      "eliminated_lb_r3": 13.99,
      "eliminated_lb_final": 13.5,
      "runner_up": 12.05,
      "champion": 9.28
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "reach_pct": {
      "ub_r1_win": 33.55,
      "ub_r2_win": 17.13,
      "ub_final_reach": 17.13,
      "ub_final_win": 8.09,
      "lb_final_reach": 20.28,
      "grand_final_reach": 17.35,
      "champion": 7.63
    },
    "outcome_pct": {
      "eliminated_lb_r1": 31.98,
      "eliminated_lb_r2": 25.74,
      "eliminated_lb_r3": 13.91,
      "eliminated_lb_final": 11.02,
      "runner_up": 9.71,
      "champion": 7.63
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "reach_pct": {
      "ub_r1_win": 72,
      "ub_r2_win": 37.32,
      "ub_final_reach": 37.32,
      "ub_final_win": 18.22,
      "lb_final_reach": 33.22,
      "grand_final_reach": 35.44,
      "champion": 17.2
    },
    "outcome_pct": {
      "eliminated_lb_r1": 13.48,
      "eliminated_lb_r2": 23.21,
      "eliminated_lb_r3": 11.87,
      "eliminated_lb_final": 16,
      "runner_up": 18.24,
      "champion": 17.2
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "reach_pct": {
      "ub_r1_win": 66.45,
      "ub_r2_win": 44.37,
      "ub_final_reach": 44.37,
      "ub_final_win": 27.86,
      "lb_final_reach": 35.43,
      "grand_final_reach": 50.66,
      "champion": 33.08
    },
    "outcome_pct": {
      "eliminated_lb_r1": 10.82,
      "eliminated_lb_r2": 15.62,
      "eliminated_lb_r3": 10.27,
      "eliminated_lb_final": 12.63,
      "runner_up": 17.58,
      "champion": 33.08
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "reach_pct": {
      "ub_r1_win": 53.01,
      "ub_r2_win": 29.51,
      "ub_final_reach": 29.51,
      "ub_final_win": 14.25,
      "lb_final_reach": 30.11,
      "grand_final_reach": 29.81,
      "champion": 14.24
    },
    "outcome_pct": {
      "eliminated_lb_r1": 16.39,
      "eliminated_lb_r2": 25.81,
      "eliminated_lb_r3": 13.44,
      "eliminated_lb_final": 14.56,
      "runner_up": 15.57,
      "champion": 14.24
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "reach_pct": {
      "ub_r1_win": 28,
      "ub_r2_win": 8.38,
      "ub_final_reach": 8.38,
      "ub_final_win": 2.34,
      "lb_final_reach": 9.95,
      "grand_final_reach": 5.31,
      "champion": 1.3
    },
    "outcome_pct": {
      "eliminated_lb_r1": 50.36,
      "eliminated_lb_r2": 28.19,
      "eliminated_lb_r3": 9.16,
      "eliminated_lb_final": 6.98,
      "runner_up": 4.01,
      "champion": 1.3
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "reach_pct": {
      "ub_r1_win": 45.51,
      "ub_r2_win": 16.76,
      "ub_final_reach": 16.76,
      "ub_final_win": 7.61,
      "lb_final_reach": 19.62,
      "grand_final_reach": 15.87,
      "champion": 6.61
    },
    "outcome_pct": {
      "eliminated_lb_r1": 32.4,
      "eliminated_lb_r2": 27.15,
      "eliminated_lb_r3": 13.23,
      "eliminated_lb_final": 11.36,
      "runner_up": 9.26,
      "champion": 6.61
    }
  }
};

export const playoffSlots: Record<string, PlayoffSlotDistribution> = {
  "ub_r1_1": {
    "a": {
      "10150413": 100
    },
    "b": {
      "7119388": 100
    },
    "winner": {
      "7119388": 54.49,
      "10150413": 45.51
    }
  },
  "ub_r1_2": {
    "a": {
      "9572001": 100
    },
    "b": {
      "8255888": 100
    },
    "winner": {
      "8255888": 33.55,
      "9572001": 66.45
    }
  },
  "ub_r1_3": {
    "a": {
      "2163": 100
    },
    "b": {
      "9823272": 100
    },
    "winner": {
      "2163": 46.99,
      "9823272": 53.01
    }
  },
  "ub_r1_4": {
    "a": {
      "10136357": 100
    },
    "b": {
      "9247354": 100
    },
    "winner": {
      "9247354": 72,
      "10136357": 28
    }
  },
  "ub_r2_1": {
    "a": {
      "7119388": 54.49,
      "10150413": 45.51
    },
    "b": {
      "8255888": 33.55,
      "9572001": 66.45
    },
    "winner": {
      "7119388": 21.75,
      "8255888": 17.13,
      "9572001": 44.37,
      "10150413": 16.76
    }
  },
  "ub_r2_2": {
    "a": {
      "2163": 46.99,
      "9823272": 53.01
    },
    "b": {
      "9247354": 72,
      "10136357": 28
    },
    "winner": {
      "2163": 24.79,
      "9247354": 37.32,
      "9823272": 29.51,
      "10136357": 8.38
    }
  },
  "lb_r1_1": {
    "a": {
      "7119388": 45.51,
      "10150413": 54.49
    },
    "b": {
      "8255888": 66.45,
      "9572001": 33.55
    },
    "winner": {
      "7119388": 20.71,
      "8255888": 34.47,
      "9572001": 22.73,
      "10150413": 22.09
    }
  },
  "lb_r1_2": {
    "a": {
      "2163": 53.01,
      "9823272": 46.99
    },
    "b": {
      "9247354": 28,
      "10136357": 72
    },
    "winner": {
      "2163": 33.24,
      "9247354": 14.52,
      "9823272": 30.61,
      "10136357": 21.64
    }
  },
  "ub_final": {
    "a": {
      "7119388": 21.75,
      "8255888": 17.13,
      "9572001": 44.37,
      "10150413": 16.76
    },
    "b": {
      "2163": 24.79,
      "9247354": 37.32,
      "9823272": 29.51,
      "10136357": 8.38
    },
    "winner": {
      "2163": 11.24,
      "7119388": 10.39,
      "8255888": 8.09,
      "9247354": 18.22,
      "9572001": 27.86,
      "9823272": 14.25,
      "10136357": 2.34,
      "10150413": 7.61
    }
  },
  "lb_r2_1": {
    "a": {
      "2163": 22.21,
      "9247354": 34.68,
      "9823272": 23.49,
      "10136357": 19.62
    },
    "b": {
      "7119388": 20.71,
      "8255888": 34.47,
      "9572001": 22.73,
      "10150413": 22.09
    },
    "winner": {
      "2163": 11.06,
      "7119388": 10.35,
      "8255888": 16.93,
      "9247354": 18.32,
      "9572001": 14.7,
      "9823272": 12.3,
      "10136357": 6.2,
      "10150413": 10.12
    }
  },
  "lb_r2_2": {
    "a": {
      "7119388": 32.74,
      "8255888": 16.43,
      "9572001": 22.08,
      "10150413": 28.75
    },
    "b": {
      "2163": 33.24,
      "9247354": 14.52,
      "9823272": 30.61,
      "10136357": 21.64
    },
    "winner": {
      "2163": 16.49,
      "7119388": 16.71,
      "8255888": 8.22,
      "9247354": 7.67,
      "9572001": 14.49,
      "9823272": 15.99,
      "10136357": 6.86,
      "10150413": 13.56
    }
  },
  "lb_r3": {
    "a": {
      "2163": 11.06,
      "7119388": 10.35,
      "8255888": 16.93,
      "9247354": 18.32,
      "9572001": 14.7,
      "9823272": 12.3,
      "10136357": 6.2,
      "10150413": 10.12
    },
    "b": {
      "2163": 16.49,
      "7119388": 16.71,
      "8255888": 8.22,
      "9247354": 7.67,
      "9572001": 14.49,
      "9823272": 15.99,
      "10136357": 6.86,
      "10150413": 13.56
    },
    "winner": {
      "2163": 13.41,
      "7119388": 13.08,
      "8255888": 11.24,
      "9247354": 14.12,
      "9572001": 18.93,
      "9823272": 14.85,
      "10136357": 3.9,
      "10150413": 10.46
    }
  },
  "lb_final": {
    "a": {
      "2163": 13.41,
      "7119388": 13.08,
      "8255888": 11.24,
      "9247354": 14.12,
      "9572001": 18.93,
      "9823272": 14.85,
      "10136357": 3.9,
      "10150413": 10.46
    },
    "b": {
      "2163": 13.55,
      "7119388": 11.36,
      "8255888": 9.04,
      "9247354": 19.1,
      "9572001": 16.5,
      "9823272": 15.26,
      "10136357": 6.04,
      "10150413": 9.15
    },
    "winner": {
      "2163": 12.99,
      "7119388": 10.94,
      "8255888": 9.26,
      "9247354": 17.22,
      "9572001": 22.8,
      "9823272": 15.56,
      "10136357": 2.97,
      "10150413": 8.26
    }
  },
  "grand_final": {
    "a": {
      "2163": 11.24,
      "7119388": 10.39,
      "8255888": 8.09,
      "9247354": 18.22,
      "9572001": 27.86,
      "9823272": 14.25,
      "10136357": 2.34,
      "10150413": 7.61
    },
    "b": {
      "2163": 12.99,
      "7119388": 10.94,
      "8255888": 9.26,
      "9247354": 17.22,
      "9572001": 22.8,
      "9823272": 15.56,
      "10136357": 2.97,
      "10150413": 8.26
    },
    "winner": {
      "2163": 10.65,
      "7119388": 9.28,
      "8255888": 7.63,
      "9247354": 17.2,
      "9572001": 33.08,
      "9823272": 14.24,
      "10136357": 1.3,
      "10150413": 6.61
    }
  }
};

export const PLAYOFF_TEAM_IDS: number[] = [2163,7119388,8255888,9247354,9572001,9823272,10136357,10150413];
