// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface PlayoffTeamResult {
  team_name: string;
  reach_pct: Record<string, number>;
  outcome_pct: Record<string, number>;
}

export interface PlayoffSimulationMeta {
  num_trials: number;
  format: string;
  best_of: { grand_final: number; default: number };
  no_bracket_reset: boolean;
  ub_r1_pairings_forced: boolean;
  ub_r1_pairings: [number, number][];
  bracket_routing: Record<string, { best_of: number; winner_to: string | null; loser_to: string | null }>;
  match_order: string[];
  reach_pct_note: string;
  outcome_pct_note: string;
}

export const playoffSimulationMeta: PlayoffSimulationMeta = {
  "num_trials": 1000000,
  "format": "double_elimination_8_team",
  "best_of": {
    "grand_final": 5,
    "default": 3
  },
  "no_bracket_reset": true,
  "ub_r1_pairings_forced": true,
  "ub_r1_pairings": [
    [
      10150413,
      7119388
    ],
    [
      9572001,
      8255888
    ],
    [
      2163,
      9823272
    ],
    [
      10136357,
      9247354
    ]
  ],
  "bracket_routing": {
    "ub_r1_1": {
      "best_of": 3,
      "winner_to": "ub_r2_1:a",
      "loser_to": "lb_r1_1:a"
    },
    "ub_r1_2": {
      "best_of": 3,
      "winner_to": "ub_r2_1:b",
      "loser_to": "lb_r1_1:b"
    },
    "ub_r1_3": {
      "best_of": 3,
      "winner_to": "ub_r2_2:a",
      "loser_to": "lb_r1_2:a"
    },
    "ub_r1_4": {
      "best_of": 3,
      "winner_to": "ub_r2_2:b",
      "loser_to": "lb_r1_2:b"
    },
    "ub_r2_1": {
      "best_of": 3,
      "winner_to": "ub_final:a",
      "loser_to": "lb_r2_2:a"
    },
    "ub_r2_2": {
      "best_of": 3,
      "winner_to": "ub_final:b",
      "loser_to": "lb_r2_1:a"
    },
    "lb_r1_1": {
      "best_of": 3,
      "winner_to": "lb_r2_1:b",
      "loser_to": null
    },
    "lb_r1_2": {
      "best_of": 3,
      "winner_to": "lb_r2_2:b",
      "loser_to": null
    },
    "ub_final": {
      "best_of": 3,
      "winner_to": "grand_final:a",
      "loser_to": "lb_final:b"
    },
    "lb_r2_1": {
      "best_of": 3,
      "winner_to": "lb_r3:a",
      "loser_to": null
    },
    "lb_r2_2": {
      "best_of": 3,
      "winner_to": "lb_r3:b",
      "loser_to": null
    },
    "lb_r3": {
      "best_of": 3,
      "winner_to": "lb_final:a",
      "loser_to": null
    },
    "lb_final": {
      "best_of": 3,
      "winner_to": "grand_final:b",
      "loser_to": null
    },
    "grand_final": {
      "best_of": 5,
      "winner_to": null,
      "loser_to": null
    }
  },
  "match_order": [
    "ub_r1_1",
    "ub_r1_2",
    "ub_r1_3",
    "ub_r1_4",
    "ub_r2_1",
    "ub_r2_2",
    "lb_r1_1",
    "lb_r1_2",
    "ub_final",
    "lb_r2_1",
    "lb_r2_2",
    "lb_r3",
    "lb_final",
    "grand_final"
  ],
  "reach_pct_note": "Probability of being alive entering / winning each named stage. ub_r1_win/ub_r2_win/ub_final_win are P(won that specific upper-bracket match); ub_final_reach/lb_final_reach/grand_final_reach are P(played in that match, win or lose); champion is P(won the Grand Final).",
  "outcome_pct_note": "Probability of being eliminated at each specific stage (mutually exclusive, sums to ~100% per team). A team is never 'eliminated' by an upper-bracket loss - it drops to the corresponding lower-bracket match and keeps playing, so the earliest possible elimination is eliminated_lb_r1."
};

export const playoffSimulation: Record<string, PlayoffTeamResult> = {
  "2163": {
    "team_name": "Team Liquid",
    "reach_pct": {
      "ub_r1_win": 49.64,
      "ub_r2_win": 25.1,
      "ub_final_reach": 25.1,
      "ub_final_win": 0.66,
      "lb_final_reach": 39.01,
      "grand_final_reach": 19.5,
      "champion": 0.16
    },
    "outcome_pct": {
      "eliminated_lb_r1": 19.3,
      "eliminated_lb_r2": 26.65,
      "eliminated_lb_r3": 14.38,
      "eliminated_lb_final": 20.17,
      "runner_up": 19.34,
      "champion": 0.16
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "reach_pct": {
      "ub_r1_win": 54.99,
      "ub_r2_win": 1.06,
      "ub_final_reach": 1.06,
      "ub_final_win": 0.51,
      "lb_final_reach": 21.4,
      "grand_final_reach": 10.52,
      "champion": 0.11
    },
    "outcome_pct": {
      "eliminated_lb_r1": 19.9,
      "eliminated_lb_r2": 37.81,
      "eliminated_lb_r3": 20.38,
      "eliminated_lb_final": 11.39,
      "runner_up": 10.4,
      "champion": 0.11
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "reach_pct": {
      "ub_r1_win": 0.98,
      "ub_r2_win": 0.47,
      "ub_final_reach": 0.47,
      "ub_final_win": 0.21,
      "lb_final_reach": 9.67,
      "grand_final_reach": 4.31,
      "champion": 0.05
    },
    "outcome_pct": {
      "eliminated_lb_r1": 51.32,
      "eliminated_lb_r2": 26.62,
      "eliminated_lb_r3": 12.18,
      "eliminated_lb_final": 5.57,
      "runner_up": 4.27,
      "champion": 0.05
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "reach_pct": {
      "ub_r1_win": 72.44,
      "ub_r2_win": 39.96,
      "ub_final_reach": 39.96,
      "ub_final_win": 1.34,
      "lb_final_reach": 54.23,
      "grand_final_reach": 31.51,
      "champion": 0.35
    },
    "outcome_pct": {
      "eliminated_lb_r1": 12.66,
      "eliminated_lb_r2": 20.03,
      "eliminated_lb_r3": 11.75,
      "eliminated_lb_final": 24.06,
      "runner_up": 31.15,
      "champion": 0.35
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "reach_pct": {
      "ub_r1_win": 99.02,
      "ub_r2_win": 97.54,
      "ub_final_reach": 97.54,
      "ub_final_win": 95.91,
      "lb_final_reach": 3.89,
      "grand_final_reach": 99.66,
      "champion": 98.98
    },
    "outcome_pct": {
      "eliminated_lb_r1": 0.03,
      "eliminated_lb_r2": 0.09,
      "eliminated_lb_r3": 0.08,
      "eliminated_lb_final": 0.15,
      "runner_up": 0.67,
      "champion": 98.98
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "reach_pct": {
      "ub_r1_win": 50.36,
      "ub_r2_win": 25.84,
      "ub_final_reach": 25.84,
      "ub_final_win": 0.73,
      "lb_final_reach": 39.88,
      "grand_final_reach": 20.39,
      "champion": 0.18
    },
    "outcome_pct": {
      "eliminated_lb_r1": 19.1,
      "eliminated_lb_r2": 26.28,
      "eliminated_lb_r3": 14.02,
      "eliminated_lb_final": 20.21,
      "runner_up": 20.22,
      "champion": 0.18
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "reach_pct": {
      "ub_r1_win": 27.56,
      "ub_r2_win": 9.1,
      "ub_final_reach": 9.1,
      "ub_final_win": 0.13,
      "lb_final_reach": 13.92,
      "grand_final_reach": 4.67,
      "champion": 0.02
    },
    "outcome_pct": {
      "eliminated_lb_r1": 48.94,
      "eliminated_lb_r2": 26.94,
      "eliminated_lb_r3": 10.06,
      "eliminated_lb_final": 9.39,
      "runner_up": 4.65,
      "champion": 0.02
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "reach_pct": {
      "ub_r1_win": 45.01,
      "ub_r2_win": 0.94,
      "ub_final_reach": 0.94,
      "ub_final_win": 0.51,
      "lb_final_reach": 18,
      "grand_final_reach": 9.45,
      "champion": 0.15
    },
    "outcome_pct": {
      "eliminated_lb_r1": 28.75,
      "eliminated_lb_r2": 35.59,
      "eliminated_lb_r3": 17.16,
      "eliminated_lb_final": 9.05,
      "runner_up": 9.3,
      "champion": 0.15
    }
  }
};

export const PLAYOFF_TEAM_IDS: number[] = [2163,7119388,8255888,9247354,9572001,9823272,10136357,10150413];
