// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface PlayoffTeamResult {
  team_name: string;
  reach_pct: Record<string, number>;
  outcome_pct: Record<string, number>;
}

export interface PlayoffSimulationMeta {
  num_trials: number;
  format: string;
  best_of: { grand_final: number; default: number };
  no_bracket_reset: boolean;
  ub_r1_pairings_forced: boolean;
  ub_r1_pairings: [number, number][];
  bracket_routing: Record<string, { best_of: number; winner_to: string | null; loser_to: string | null }>;
  match_order: string[];
  reach_pct_note: string;
  outcome_pct_note: string;
}

export const playoffSimulationMeta: PlayoffSimulationMeta = {
  "num_trials": 1000000,
  "format": "double_elimination_8_team",
  "best_of": {
    "grand_final": 5,
    "default": 3
  },
  "no_bracket_reset": true,
  "ub_r1_pairings_forced": true,
  "ub_r1_pairings": [
    [
      10150413,
      7119388
    ],
    [
      9572001,
      8255888
    ],
    [
      2163,
      9823272
    ],
    [
      10136357,
      9247354
    ]
  ],
  "bracket_routing": {
    "ub_r1_1": {
      "best_of": 3,
      "winner_to": "ub_r2_1:a",
      "loser_to": "lb_r1_1:a"
    },
    "ub_r1_2": {
      "best_of": 3,
      "winner_to": "ub_r2_1:b",
      "loser_to": "lb_r1_1:b"
    },
    "ub_r1_3": {
      "best_of": 3,
      "winner_to": "ub_r2_2:a",
      "loser_to": "lb_r1_2:a"
    },
    "ub_r1_4": {
      "best_of": 3,
      "winner_to": "ub_r2_2:b",
      "loser_to": "lb_r1_2:b"
    },
    "ub_r2_1": {
      "best_of": 3,
      "winner_to": "ub_final:a",
      "loser_to": "lb_r2_2:a"
    },
    "ub_r2_2": {
      "best_of": 3,
      "winner_to": "ub_final:b",
      "loser_to": "lb_r2_1:a"
    },
    "lb_r1_1": {
      "best_of": 3,
      "winner_to": "lb_r2_1:b",
      "loser_to": null
    },
    "lb_r1_2": {
      "best_of": 3,
      "winner_to": "lb_r2_2:b",
      "loser_to": null
    },
    "ub_final": {
      "best_of": 3,
      "winner_to": "grand_final:a",
      "loser_to": "lb_final:b"
    },
    "lb_r2_1": {
      "best_of": 3,
      "winner_to": "lb_r3:a",
      "loser_to": null
    },
    "lb_r2_2": {
      "best_of": 3,
      "winner_to": "lb_r3:b",
      "loser_to": null
    },
    "lb_r3": {
      "best_of": 3,
      "winner_to": "lb_final:a",
      "loser_to": null
    },
    "lb_final": {
      "best_of": 3,
      "winner_to": "grand_final:b",
      "loser_to": null
    },
    "grand_final": {
      "best_of": 5,
      "winner_to": null,
      "loser_to": null
    }
  },
  "match_order": [
    "ub_r1_1",
    "ub_r1_2",
    "ub_r1_3",
    "ub_r1_4",
    "ub_r2_1",
    "ub_r2_2",
    "lb_r1_1",
    "lb_r1_2",
    "ub_final",
    "lb_r2_1",
    "lb_r2_2",
    "lb_r3",
    "lb_final",
    "grand_final"
  ],
  "reach_pct_note": "Probability of being alive entering / winning each named stage. ub_r1_win/ub_r2_win/ub_final_win are P(won that specific upper-bracket match); ub_final_reach/lb_final_reach/grand_final_reach are P(played in that match, win or lose); champion is P(won the Grand Final).",
  "outcome_pct_note": "Probability of being eliminated at each specific stage (mutually exclusive, sums to ~100% per team). A team is never 'eliminated' by an upper-bracket loss - it drops to the corresponding lower-bracket match and keeps playing, so the earliest possible elimination is eliminated_lb_r1."
};

export const playoffSimulation: Record<string, PlayoffTeamResult> = {
  "2163": {
    "team_name": "Team Liquid",
    "reach_pct": {
      "ub_r1_win": 49.02,
      "ub_r2_win": 25.92,
      "ub_final_reach": 25.92,
      "ub_final_win": 11.39,
      "lb_final_reach": 27.6,
      "grand_final_reach": 24.82,
      "champion": 10.54
    },
    "outcome_pct": {
      "eliminated_lb_r1": 20.99,
      "eliminated_lb_r2": 26.65,
      "eliminated_lb_r3": 13.39,
      "eliminated_lb_final": 14.17,
      "runner_up": 14.28,
      "champion": 10.54
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "reach_pct": {
      "ub_r1_win": 53.59,
      "ub_r2_win": 20.32,
      "ub_final_reach": 20.32,
      "ub_final_win": 9.79,
      "lb_final_reach": 23.66,
      "grand_final_reach": 20.24,
      "champion": 8.62
    },
    "outcome_pct": {
      "eliminated_lb_r1": 25.09,
      "eliminated_lb_r2": 27.22,
      "eliminated_lb_r3": 14.25,
      "eliminated_lb_final": 13.21,
      "runner_up": 11.62,
      "champion": 8.62
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "reach_pct": {
      "ub_r1_win": 30.12,
      "ub_r2_win": 14.98,
      "ub_final_reach": 14.98,
      "ub_final_win": 6.96,
      "lb_final_reach": 18.43,
      "grand_final_reach": 15,
      "champion": 6.29
    },
    "outcome_pct": {
      "eliminated_lb_r1": 34.6,
      "eliminated_lb_r2": 26.22,
      "eliminated_lb_r3": 13.79,
      "eliminated_lb_final": 10.4,
      "runner_up": 8.71,
      "champion": 6.29
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "reach_pct": {
      "ub_r1_win": 67.04,
      "ub_r2_win": 34.99,
      "ub_final_reach": 34.99,
      "ub_final_win": 16.36,
      "lb_final_reach": 32.52,
      "grand_final_reach": 33.13,
      "champion": 15.27
    },
    "outcome_pct": {
      "eliminated_lb_r1": 15.76,
      "eliminated_lb_r2": 23.41,
      "eliminated_lb_r3": 11.95,
      "eliminated_lb_final": 15.76,
      "runner_up": 17.86,
      "champion": 15.27
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "reach_pct": {
      "ub_r1_win": 69.88,
      "ub_r2_win": 48.2,
      "ub_final_reach": 48.2,
      "ub_final_win": 31.73,
      "lb_final_reach": 35.88,
      "grand_final_reach": 55.71,
      "champion": 38.51
    },
    "outcome_pct": {
      "eliminated_lb_r1": 9.12,
      "eliminated_lb_r2": 13.91,
      "eliminated_lb_r3": 9.36,
      "eliminated_lb_final": 11.89,
      "runner_up": 17.2,
      "champion": 38.51
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "reach_pct": {
      "ub_r1_win": 50.98,
      "ub_r2_win": 27.45,
      "ub_final_reach": 27.45,
      "ub_final_win": 12.45,
      "lb_final_reach": 28.53,
      "grand_final_reach": 26.75,
      "champion": 11.76
    },
    "outcome_pct": {
      "eliminated_lb_r1": 19.8,
      "eliminated_lb_r2": 26.04,
      "eliminated_lb_r3": 13.18,
      "eliminated_lb_final": 14.23,
      "runner_up": 14.99,
      "champion": 11.76
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "reach_pct": {
      "ub_r1_win": 32.96,
      "ub_r2_win": 11.64,
      "ub_final_reach": 11.64,
      "ub_final_win": 3.63,
      "lb_final_reach": 13.59,
      "grand_final_reach": 8.27,
      "champion": 2.27
    },
    "outcome_pct": {
      "eliminated_lb_r1": 43.45,
      "eliminated_lb_r2": 28.74,
      "eliminated_lb_r3": 10.59,
      "eliminated_lb_final": 8.96,
      "runner_up": 6,
      "champion": 2.27
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "reach_pct": {
      "ub_r1_win": 46.41,
      "ub_r2_win": 16.51,
      "ub_final_reach": 16.51,
      "ub_final_win": 7.69,
      "lb_final_reach": 19.79,
      "grand_final_reach": 16.08,
      "champion": 6.74
    },
    "outcome_pct": {
      "eliminated_lb_r1": 31.19,
      "eliminated_lb_r2": 27.81,
      "eliminated_lb_r3": 13.51,
      "eliminated_lb_final": 11.39,
      "runner_up": 9.35,
      "champion": 6.74
    }
  }
};

export const PLAYOFF_TEAM_IDS: number[] = [2163,7119388,8255888,9247354,9572001,9823272,10136357,10150413];
