// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface TeamSimOutcome {
  team_name: string;
  outcome_pct: Record<string, number>;
}

export interface SimulationRun {
  meta: { num_trials: number; max_rounds: number; wins_to_advance: number; losses_to_eliminate: number };
  teams: Record<string, TeamSimOutcome>;
}

export const precomputedSimulations: Record<number, SimulationRun> = {
  10000: { meta: {"num_trials":10000,"max_rounds":5,"wins_to_advance":4,"losses_to_eliminate":4}, teams: {
  "2163": {
    "team_name": "Team Liquid",
    "outcome_pct": {
      "4-0": 9.38,
      "4-1": 19.17,
      "3-2": 41.5,
      "2-3": 24.72,
      "1-4": 4.09,
      "0-4": 1.14
    }
  },
  "726228": {
    "team_name": "Vici Gaming",
    "outcome_pct": {
      "4-0": 1.48,
      "4-1": 5.33,
      "3-2": 26.54,
      "2-3": 41.54,
      "1-4": 17.83,
      "0-4": 7.28
    }
  },
  "2586976": {
    "team_name": "OG",
    "outcome_pct": {
      "4-0": 1.18,
      "4-1": 4.19,
      "3-2": 24.44,
      "2-3": 41.39,
      "1-4": 19.63,
      "0-4": 9.17
    }
  },
  "5017210": {
    "team_name": "Team Resilience",
    "outcome_pct": {
      "4-0": 0.62,
      "4-1": 1.87,
      "3-2": 13.36,
      "2-3": 35.3,
      "1-4": 27.83,
      "0-4": 21.02
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "outcome_pct": {
      "4-0": 9.92,
      "4-1": 19.55,
      "3-2": 41.42,
      "2-3": 23.69,
      "1-4": 4.29,
      "0-4": 1.13
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "outcome_pct": {
      "4-0": 10.18,
      "4-1": 20.55,
      "3-2": 41.38,
      "2-3": 22.91,
      "1-4": 3.76,
      "0-4": 1.22
    }
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "outcome_pct": {
      "4-0": 2.66,
      "4-1": 7.88,
      "3-2": 34.11,
      "2-3": 38.74,
      "1-4": 12,
      "0-4": 4.61
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "outcome_pct": {
      "4-0": 13.39,
      "4-1": 24.88,
      "3-2": 40.06,
      "2-3": 18.4,
      "1-4": 2.53,
      "0-4": 0.74
    }
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "outcome_pct": {
      "4-0": 10.04,
      "4-1": 20.62,
      "3-2": 41.57,
      "2-3": 22.87,
      "1-4": 3.9,
      "0-4": 1
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "outcome_pct": {
      "4-0": 17.41,
      "4-1": 27.7,
      "3-2": 38.06,
      "2-3": 14.82,
      "1-4": 1.67,
      "0-4": 0.34
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "outcome_pct": {
      "4-0": 14.95,
      "4-1": 26.76,
      "3-2": 39.24,
      "2-3": 16.63,
      "1-4": 1.95,
      "0-4": 0.47
    }
  },
  "9964962": {
    "team_name": "GamerLegion",
    "outcome_pct": {
      "4-0": 0.51,
      "4-1": 2.39,
      "3-2": 17.17,
      "2-3": 39.47,
      "1-4": 26.54,
      "0-4": 13.92
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "outcome_pct": {
      "4-0": 1.28,
      "4-1": 4.43,
      "3-2": 25.35,
      "2-3": 42.63,
      "1-4": 18.44,
      "0-4": 7.87
    }
  },
  "10149530": {
    "team_name": "HULIGANI",
    "outcome_pct": {
      "4-0": 0.43,
      "4-1": 1.4,
      "3-2": 12.37,
      "2-3": 35.67,
      "1-4": 29.49,
      "0-4": 20.64
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "outcome_pct": {
      "4-0": 5.58,
      "4-1": 14.08,
      "3-2": 38.5,
      "2-3": 31.58,
      "1-4": 7.88,
      "0-4": 2.38
    }
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "outcome_pct": {
      "4-0": 0.99,
      "4-1": 4.05,
      "3-2": 22.51,
      "2-3": 40.78,
      "1-4": 21.59,
      "0-4": 10.08
    }
  }
} },
  100000: { meta: {"num_trials":100000,"max_rounds":5,"wins_to_advance":4,"losses_to_eliminate":4}, teams: {
  "2163": {
    "team_name": "Team Liquid",
    "outcome_pct": {
      "4-0": 9.02,
      "4-1": 19.36,
      "3-2": 41.31,
      "2-3": 24.77,
      "1-4": 4.31,
      "0-4": 1.22
    }
  },
  "726228": {
    "team_name": "Vici Gaming",
    "outcome_pct": {
      "4-0": 1.61,
      "4-1": 5.24,
      "3-2": 27.07,
      "2-3": 41.69,
      "1-4": 17.27,
      "0-4": 7.12
    }
  },
  "2586976": {
    "team_name": "OG",
    "outcome_pct": {
      "4-0": 1.24,
      "4-1": 4.2,
      "3-2": 24.38,
      "2-3": 41.93,
      "1-4": 19.58,
      "0-4": 8.68
    }
  },
  "5017210": {
    "team_name": "Team Resilience",
    "outcome_pct": {
      "4-0": 0.57,
      "4-1": 1.96,
      "3-2": 13.57,
      "2-3": 34.95,
      "1-4": 28.42,
      "0-4": 20.53
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "outcome_pct": {
      "4-0": 9.53,
      "4-1": 20.17,
      "3-2": 41.17,
      "2-3": 23.95,
      "1-4": 4.1,
      "0-4": 1.08
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "outcome_pct": {
      "4-0": 9.88,
      "4-1": 20.58,
      "3-2": 40.88,
      "2-3": 23.74,
      "1-4": 3.8,
      "0-4": 1.12
    }
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "outcome_pct": {
      "4-0": 2.65,
      "4-1": 8.1,
      "3-2": 33.4,
      "2-3": 38.84,
      "1-4": 12.42,
      "0-4": 4.58
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "outcome_pct": {
      "4-0": 13.79,
      "4-1": 24.78,
      "3-2": 39.86,
      "2-3": 18.36,
      "1-4": 2.58,
      "0-4": 0.63
    }
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "outcome_pct": {
      "4-0": 9.98,
      "4-1": 20.55,
      "3-2": 41.43,
      "2-3": 23.12,
      "1-4": 3.88,
      "0-4": 1.04
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "outcome_pct": {
      "4-0": 17.38,
      "4-1": 27.79,
      "3-2": 37.91,
      "2-3": 14.74,
      "1-4": 1.77,
      "0-4": 0.42
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "outcome_pct": {
      "4-0": 15.32,
      "4-1": 26.36,
      "3-2": 38.89,
      "2-3": 16.73,
      "1-4": 2.15,
      "0-4": 0.55
    }
  },
  "9964962": {
    "team_name": "GamerLegion",
    "outcome_pct": {
      "4-0": 0.53,
      "4-1": 2.3,
      "3-2": 17.09,
      "2-3": 40.08,
      "1-4": 26.14,
      "0-4": 13.85
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "outcome_pct": {
      "4-0": 1.42,
      "4-1": 4.65,
      "3-2": 25.59,
      "2-3": 41.81,
      "1-4": 18.45,
      "0-4": 8.08
    }
  },
  "10149530": {
    "team_name": "HULIGANI",
    "outcome_pct": {
      "4-0": 0.44,
      "4-1": 1.55,
      "3-2": 12.49,
      "2-3": 34.56,
      "1-4": 29.75,
      "0-4": 21.2
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "outcome_pct": {
      "4-0": 5.53,
      "4-1": 13.72,
      "3-2": 38.89,
      "2-3": 31.85,
      "1-4": 7.62,
      "0-4": 2.4
    }
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "outcome_pct": {
      "4-0": 1.1,
      "4-1": 3.89,
      "3-2": 22.45,
      "2-3": 41.15,
      "1-4": 21.29,
      "0-4": 10.12
    }
  }
} },
};
