// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface TeamSimOutcome {
  team_name: string;
  outcome_pct: Record<string, number>;
}

export interface SimulationMeta {
  num_trials: number;
  max_rounds: number;
  wins_to_advance: number;
  losses_to_eliminate: number;
  day1_pairings_forced: boolean;
  day1_pairings: [number, number][];
  day1_note: string;
}

export interface SimulationRun {
  meta: SimulationMeta;
  teams: Record<string, TeamSimOutcome>;
}

export const precomputedSimulation: SimulationRun = { meta: {
  "num_trials": 1000000,
  "max_rounds": 5,
  "wins_to_advance": 4,
  "losses_to_eliminate": 4,
  "day1_pairings_forced": true,
  "day1_pairings": [
    [
      9247354,
      10150538
    ],
    [
      10150413,
      10136357
    ],
    [
      8255888,
      2586976
    ],
    [
      9572001,
      5017210
    ],
    [
      7119388,
      8261500
    ],
    [
      2163,
      726228
    ],
    [
      9467224,
      9964962
    ],
    [
      9823272,
      10149530
    ]
  ],
  "day1_note": "Round 1 of every trial uses these announced Day 1 (Aug 13) pairings directly instead of the standings-based approximation, so the outcome distribution already reflects each team's real first opponent."
}, teams: {
  "2163": {
    "team_name": "Team Liquid",
    "outcome_pct": {
      "4-0": 8.68,
      "4-1": 19.52,
      "3-2": 42.72,
      "2-3": 24.51,
      "1-4": 3.76,
      "0-4": 0.81
    }
  },
  "726228": {
    "team_name": "Vici Gaming",
    "outcome_pct": {
      "4-0": 1.07,
      "4-1": 4.76,
      "3-2": 27.14,
      "2-3": 42.76,
      "1-4": 17.25,
      "0-4": 7.02
    }
  },
  "2586976": {
    "team_name": "OG",
    "outcome_pct": {
      "4-0": 0.81,
      "4-1": 3.76,
      "3-2": 24.12,
      "2-3": 43.05,
      "1-4": 19.72,
      "0-4": 8.55
    }
  },
  "5017210": {
    "team_name": "Team Resilience",
    "outcome_pct": {
      "4-0": 0.32,
      "4-1": 1.67,
      "3-2": 13.02,
      "2-3": 34.9,
      "1-4": 28.8,
      "0-4": 21.3
    }
  },
  "7119388": {
    "team_name": "Team Spirit",
    "outcome_pct": {
      "4-0": 8.63,
      "4-1": 19.97,
      "3-2": 42.8,
      "2-3": 24.12,
      "1-4": 3.63,
      "0-4": 0.85
    }
  },
  "8255888": {
    "team_name": "BoomBoys",
    "outcome_pct": {
      "4-0": 9.8,
      "4-1": 21.05,
      "3-2": 42.36,
      "2-3": 22.78,
      "1-4": 3.31,
      "0-4": 0.69
    }
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "outcome_pct": {
      "4-0": 1.86,
      "4-1": 7.36,
      "3-2": 33.19,
      "2-3": 40.31,
      "1-4": 12.77,
      "0-4": 4.52
    }
  },
  "9247354": {
    "team_name": "Team Falcons",
    "outcome_pct": {
      "4-0": 14.38,
      "4-1": 25.58,
      "3-2": 40.44,
      "2-3": 17.17,
      "1-4": 2.04,
      "0-4": 0.39
    }
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "outcome_pct": {
      "4-0": 10.63,
      "4-1": 21.43,
      "3-2": 41.99,
      "2-3": 22.1,
      "1-4": 3.23,
      "0-4": 0.62
    }
  },
  "9572001": {
    "team_name": "Team Vision",
    "outcome_pct": {
      "4-0": 19.14,
      "4-1": 28.95,
      "3-2": 37.39,
      "2-3": 13.04,
      "1-4": 1.28,
      "0-4": 0.21
    }
  },
  "9823272": {
    "team_name": "Team Yandex",
    "outcome_pct": {
      "4-0": 16.97,
      "4-1": 27.28,
      "3-2": 38.79,
      "2-3": 15.01,
      "1-4": 1.67,
      "0-4": 0.28
    }
  },
  "9964962": {
    "team_name": "GamerLegion",
    "outcome_pct": {
      "4-0": 0.38,
      "4-1": 1.98,
      "3-2": 16.92,
      "2-3": 41.06,
      "1-4": 25.88,
      "0-4": 13.79
    }
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "outcome_pct": {
      "4-0": 1.08,
      "4-1": 4.4,
      "3-2": 26.2,
      "2-3": 42.85,
      "1-4": 18.19,
      "0-4": 7.28
    }
  },
  "10149530": {
    "team_name": "HULIGANI",
    "outcome_pct": {
      "4-0": 0.23,
      "4-1": 1.32,
      "3-2": 12.02,
      "2-3": 35.2,
      "1-4": 29.71,
      "0-4": 21.52
    }
  },
  "10150413": {
    "team_name": "Iron Wing",
    "outcome_pct": {
      "4-0": 5.61,
      "4-1": 14.11,
      "3-2": 40.29,
      "2-3": 31.49,
      "1-4": 6.78,
      "0-4": 1.72
    }
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "outcome_pct": {
      "4-0": 0.42,
      "4-1": 2.27,
      "3-2": 17.54,
      "2-3": 40.69,
      "1-4": 25.27,
      "0-4": 13.82
    }
  }
} };
