// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface TeamSimOutcome {
  team_name: string;
  outcome_pct: Record<string, number>;
  advance_pct: number;
}

export interface SimulationMeta {
  num_trials: number;
  max_rounds: number;
  wins_to_advance: number;
  losses_to_eliminate: number;
  day1_pairings_forced: boolean;
  day1_pairings: [number, number][];
  day1_note: string;
  podded_rounds: number;
  team_pod: Record<string, string>;
  pod_note: string;
  decider_round: number;
  decider_note: string;
  outcome_order: string[];
  outcome_labels: Record<string, string>;
  advancing_outcomes: string[];
}

export interface SimulationRun {
  meta: SimulationMeta;
  teams: Record<string, TeamSimOutcome>;
}

export const precomputedSimulation: SimulationRun = { meta: {
  "num_trials": 1000000,
  "max_rounds": 6,
  "wins_to_advance": 4,
  "losses_to_eliminate": 4,
  "day1_pairings_forced": true,
  "day1_pairings": [
    [
      9247354,
      10150538
    ],
    [
      10150413,
      10136357
    ],
    [
      8255888,
      2586976
    ],
    [
      9572001,
      5017210
    ],
    [
      7119388,
      8261500
    ],
    [
      2163,
      726228
    ],
    [
      9467224,
      9964962
    ],
    [
      9823272,
      10149530
    ]
  ],
  "day1_note": "Round 1 of every trial uses these announced Day 1 (Aug 13) pairings directly instead of the standings-based approximation, so the outcome distribution already reflects each team's real first opponent.",
  "podded_rounds": 3,
  "team_pod": {
    "2163": "B",
    "726228": "B",
    "2586976": "A",
    "5017210": "A",
    "7119388": "B",
    "8255888": "A",
    "8261500": "B",
    "9247354": "A",
    "9467224": "B",
    "9572001": "A",
    "9823272": "B",
    "9964962": "B",
    "10136357": "A",
    "10149530": "B",
    "10150413": "A",
    "10150538": "A"
  },
  "pod_note": "Rounds 1-3 (0-indexed 0..2) pair teams only against others in their own pod (A/B, confirmed from real TI2025 results and TI2026's announced Day 1 pairings). Rounds 4-5 are a single merged 16-team Swiss.",
  "decider_round": 6,
  "decider_note": "Round 6 is the elimination day: every team not already at 4 wins or 4 losses plays one final match - the winner qualifies and the loser is out, whatever their record. This is why 3-3 appears as both a qualifying and an eliminating outcome, and why 4-3/3-4 are impossible (there is no 7th round). Reconstructed from real TI2025 Day 4 results.",
  "outcome_order": [
    "4-0",
    "4-1",
    "4-2",
    "3-3a",
    "3-3e",
    "2-4",
    "1-4",
    "0-4"
  ],
  "outcome_labels": {
    "4-0": "4-0",
    "4-1": "4-1",
    "4-2": "4-2",
    "3-3a": "3-3 (in)",
    "3-3e": "3-3 (out)",
    "2-4": "2-4",
    "1-4": "1-4",
    "0-4": "0-4"
  },
  "advancing_outcomes": [
    "4-0",
    "4-1",
    "4-2",
    "3-3a"
  ]
}, teams: {
  "2163": {
    "team_name": "Team Liquid",
    "outcome_pct": {
      "4-0": 8.53,
      "4-1": 19.02,
      "4-2": 28.23,
      "3-3a": 13.87,
      "3-3e": 15.08,
      "2-4": 10.98,
      "1-4": 3.54,
      "0-4": 0.76
    },
    "advance_pct": 69.64
  },
  "726228": {
    "team_name": "Vici Gaming",
    "outcome_pct": {
      "4-0": 1.04,
      "4-1": 4.37,
      "4-2": 12.38,
      "3-3a": 15.96,
      "3-3e": 14.38,
      "2-4": 28.03,
      "1-4": 17.16,
      "0-4": 6.68
    },
    "advance_pct": 33.75
  },
  "2586976": {
    "team_name": "OG",
    "outcome_pct": {
      "4-0": 0.83,
      "4-1": 3.58,
      "4-2": 10.66,
      "3-3a": 15.17,
      "3-3e": 13.63,
      "2-4": 29.11,
      "1-4": 19.16,
      "0-4": 7.86
    },
    "advance_pct": 30.24
  },
  "5017210": {
    "team_name": "Team Resilience",
    "outcome_pct": {
      "4-0": 0.33,
      "4-1": 1.53,
      "4-2": 4.83,
      "3-3a": 9.69,
      "3-3e": 7.98,
      "2-4": 26.25,
      "1-4": 28.6,
      "0-4": 20.79
    },
    "advance_pct": 16.38
  },
  "7119388": {
    "team_name": "Team Spirit",
    "outcome_pct": {
      "4-0": 8.58,
      "4-1": 19.5,
      "4-2": 28.73,
      "3-3a": 13.65,
      "3-3e": 14.78,
      "2-4": 10.57,
      "1-4": 3.45,
      "0-4": 0.75
    },
    "advance_pct": 70.46
  },
  "8255888": {
    "team_name": "BoomBoys",
    "outcome_pct": {
      "4-0": 9.65,
      "4-1": 20.69,
      "4-2": 28.61,
      "3-3a": 12.96,
      "3-3e": 14.52,
      "2-4": 9.84,
      "1-4": 3.11,
      "0-4": 0.62
    },
    "advance_pct": 71.91
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "outcome_pct": {
      "4-0": 1.83,
      "4-1": 6.92,
      "4-2": 17.24,
      "3-3a": 17.14,
      "3-3e": 16.04,
      "2-4": 24.27,
      "1-4": 12.34,
      "0-4": 4.22
    },
    "advance_pct": 43.13
  },
  "9247354": {
    "team_name": "Team Falcons",
    "outcome_pct": {
      "4-0": 14.45,
      "4-1": 25.17,
      "4-2": 28.78,
      "3-3a": 10.5,
      "3-3e": 12.31,
      "2-4": 6.59,
      "1-4": 1.85,
      "0-4": 0.34
    },
    "advance_pct": 78.91
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "outcome_pct": {
      "4-0": 10.49,
      "4-1": 20.79,
      "4-2": 28.21,
      "3-3a": 12.72,
      "3-3e": 14.41,
      "2-4": 9.69,
      "1-4": 3.07,
      "0-4": 0.63
    },
    "advance_pct": 72.21
  },
  "9572001": {
    "team_name": "Team Vision",
    "outcome_pct": {
      "4-0": 19.58,
      "4-1": 28.58,
      "4-2": 27.45,
      "3-3a": 8.33,
      "3-3e": 10.17,
      "2-4": 4.48,
      "1-4": 1.19,
      "0-4": 0.2
    },
    "advance_pct": 83.95
  },
  "9823272": {
    "team_name": "Team Yandex",
    "outcome_pct": {
      "4-0": 17.24,
      "4-1": 26.9,
      "4-2": 27.96,
      "3-3a": 9.31,
      "3-3e": 11.21,
      "2-4": 5.51,
      "1-4": 1.57,
      "0-4": 0.29
    },
    "advance_pct": 81.41
  },
  "9964962": {
    "team_name": "GamerLegion",
    "outcome_pct": {
      "4-0": 0.37,
      "4-1": 1.79,
      "4-2": 6.08,
      "3-3a": 12,
      "3-3e": 10.19,
      "2-4": 29.93,
      "1-4": 25.99,
      "0-4": 13.65
    },
    "advance_pct": 20.24
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "outcome_pct": {
      "4-0": 1.03,
      "4-1": 4.15,
      "4-2": 11.85,
      "3-3a": 15.47,
      "3-3e": 14.49,
      "2-4": 28.67,
      "1-4": 17.72,
      "0-4": 6.62
    },
    "advance_pct": 32.49
  },
  "10149530": {
    "team_name": "HULIGANI",
    "outcome_pct": {
      "4-0": 0.25,
      "4-1": 1.15,
      "4-2": 3.99,
      "3-3a": 9.08,
      "3-3e": 7.39,
      "2-4": 26.26,
      "1-4": 29.86,
      "0-4": 22.03
    },
    "advance_pct": 14.47
  },
  "10150413": {
    "team_name": "Iron Wing",
    "outcome_pct": {
      "4-0": 5.36,
      "4-1": 13.75,
      "4-2": 24.37,
      "3-3a": 15.5,
      "3-3e": 16.53,
      "2-4": 16.57,
      "1-4": 6.39,
      "0-4": 1.53
    },
    "advance_pct": 58.99
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "outcome_pct": {
      "4-0": 0.44,
      "4-1": 2.09,
      "4-2": 6.84,
      "3-3a": 12.46,
      "3-3e": 10.67,
      "2-4": 29.47,
      "1-4": 25.01,
      "0-4": 13.03
    },
    "advance_pct": 21.82
  }
} };
