// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface TeamStability {
  team_name: string;
  matches_with_curve: number;
  effective_n: number;
  avg_draft_stage_win_rate: number | null;
  draft_favored_win_rate: number | null;
  draft_favored_sample_weight: number;
  draft_underdog_win_rate: number | null;
  draft_underdog_sample_weight: number;
  choke_rate: number | null;
  choke_rate_sample_weight: number;
  comeback_rate: number | null;
  comeback_rate_sample_weight: number;
  avg_volatility: number | null;
}

export const stabilityMeta = {
  "choke_threshold": 0.7,
  "comeback_threshold": 0.3,
  "note": "avg_draft_stage_win_rate = decayed/tier-weighted average of predicted_win_rates[0] - Stratz's predicted win% immediately after the draft, before any in-game events - i.e. 'how good is this team's draft' on its own. draft_favored_win_rate/draft_underdog_win_rate = P(actual win | draft-stage prediction was >0.5 / <=0.5) - whether a good draft actually converts into a win and whether they can overcome a bad one; this is the draft-stage-specific analogue of choke_rate/comeback_rate below (0.5 threshold, single draft-stage value) as opposed to those (0.70/0.30 threshold, anywhere in the match). choke_rate = P(lose | was predicted >=70% favorite at some point in the match). comeback_rate = P(win | was predicted <=30% at some point). All rates are decayed/tier-weighted like the main rating. avg_volatility = average (peak-trough) swing in predicted win% across a team's games - higher means more rollercoaster games, lower means more control/dominant closeouts."
};

export const teamStability: Record<string, TeamStability> = {
  "2163": {
    "team_name": "Team Liquid",
    "matches_with_curve": 271,
    "effective_n": 69.0800330331584,
    "avg_draft_stage_win_rate": 0.4878216494627085,
    "draft_favored_win_rate": 0.5428257674920638,
    "draft_favored_sample_weight": 33.131404222576286,
    "draft_underdog_win_rate": 0.5371359163546126,
    "draft_underdog_sample_weight": 35.948628810582086,
    "choke_rate": 0.5242404965825556,
    "choke_rate_sample_weight": 19.40524856371852,
    "comeback_rate": 0.511762085654862,
    "comeback_rate_sample_weight": 24.136116768736578,
    "avg_volatility": 0.3078432624927209
  },
  "726228": {
    "team_name": "Vici Gaming",
    "matches_with_curve": 59,
    "effective_n": 34.62763472471987,
    "avg_draft_stage_win_rate": 0.5046094521443342,
    "draft_favored_win_rate": 0.33734231731502445,
    "draft_favored_sample_weight": 19.13739690250456,
    "draft_underdog_win_rate": 0.5833064340999866,
    "draft_underdog_sample_weight": 15.4902378222153,
    "choke_rate": 0.7200588049174343,
    "choke_rate_sample_weight": 12.07099537295523,
    "comeback_rate": 0.44434685775611393,
    "comeback_rate_sample_weight": 10.467056509077189,
    "avg_volatility": 0.30776805195216983
  },
  "2586976": {
    "team_name": "OG",
    "matches_with_curve": 78,
    "effective_n": 37.81168468885224,
    "avg_draft_stage_win_rate": 0.5088194166021783,
    "draft_favored_win_rate": 0.3989784373068745,
    "draft_favored_sample_weight": 19.425714732421476,
    "draft_underdog_win_rate": 0.4377553620504954,
    "draft_underdog_sample_weight": 18.385969956430756,
    "choke_rate": 0.706449280324214,
    "choke_rate_sample_weight": 10.07694136121508,
    "comeback_rate": 0.44655951901046587,
    "comeback_rate_sample_weight": 10.208480971098489,
    "avg_volatility": 0.30697046510186166
  },
  "5017210": {
    "team_name": "Team Resilience",
    "matches_with_curve": 9,
    "effective_n": 3.27389487612081,
    "avg_draft_stage_win_rate": 0.5024770237589944,
    "draft_favored_win_rate": 0,
    "draft_favored_sample_weight": 1.2193544985485434,
    "draft_underdog_win_rate": 0,
    "draft_underdog_sample_weight": 2.054540377572266,
    "choke_rate": 1,
    "choke_rate_sample_weight": 1.2193544985485434,
    "comeback_rate": 0,
    "comeback_rate_sample_weight": 1.027295018694716,
    "avg_volatility": 0.32940042827322874
  },
  "7119388": {
    "team_name": "Team Spirit",
    "matches_with_curve": 264,
    "effective_n": 62.9878363832884,
    "avg_draft_stage_win_rate": 0.51552804280515,
    "draft_favored_win_rate": 0.5865139272425237,
    "draft_favored_sample_weight": 33.51168869376954,
    "draft_underdog_win_rate": 0.5607354600531115,
    "draft_underdog_sample_weight": 29.476147689518882,
    "choke_rate": 0.3249888694291784,
    "choke_rate_sample_weight": 22.22206147753687,
    "comeback_rate": 0.48083755103741277,
    "comeback_rate_sample_weight": 21.35743989167167,
    "avg_volatility": 0.316339367201752
  },
  "8255888": {
    "team_name": "BoomBoys",
    "matches_with_curve": 264,
    "effective_n": 61.5383417364996,
    "avg_draft_stage_win_rate": 0.4871005494178986,
    "draft_favored_win_rate": 0.47994688430848553,
    "draft_favored_sample_weight": 29.175836185926173,
    "draft_underdog_win_rate": 0.5151116530933654,
    "draft_underdog_sample_weight": 32.36250555057345,
    "choke_rate": 0.5245301817198245,
    "choke_rate_sample_weight": 20.416313883239248,
    "comeback_rate": 0.6065390870552306,
    "comeback_rate_sample_weight": 19.60766066729934,
    "avg_volatility": 0.3073400512121278
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "matches_with_curve": 134,
    "effective_n": 50.322165785009446,
    "avg_draft_stage_win_rate": 0.46775748119434035,
    "draft_favored_win_rate": 0.4919704127267338,
    "draft_favored_sample_weight": 23.192318900107423,
    "draft_underdog_win_rate": 0.43415624604136527,
    "draft_underdog_sample_weight": 27.129846884901987,
    "choke_rate": 0.4802816634254913,
    "choke_rate_sample_weight": 11.927114784725449,
    "comeback_rate": 0.31345436409218547,
    "comeback_rate_sample_weight": 18.800671326697564,
    "avg_volatility": 0.2930734190067447
  },
  "9247354": {
    "team_name": "Team Falcons",
    "matches_with_curve": 281,
    "effective_n": 74.18088003951151,
    "avg_draft_stage_win_rate": 0.4725677105891545,
    "draft_favored_win_rate": 0.5524515127979719,
    "draft_favored_sample_weight": 34.28819538315435,
    "draft_underdog_win_rate": 0.6368615288890537,
    "draft_underdog_sample_weight": 39.892684656357154,
    "choke_rate": 0.5184616412506771,
    "choke_rate_sample_weight": 24.31119379493038,
    "comeback_rate": 0.6156516862152535,
    "comeback_rate_sample_weight": 27.348440746538266,
    "avg_volatility": 0.32181789049707776
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "matches_with_curve": 139,
    "effective_n": 67.25089181805612,
    "avg_draft_stage_win_rate": 0.46607130014102277,
    "draft_favored_win_rate": 0.6205944357398632,
    "draft_favored_sample_weight": 30.026408268779782,
    "draft_underdog_win_rate": 0.5673939974135265,
    "draft_underdog_sample_weight": 37.22448354927635,
    "choke_rate": 0.35043657432977526,
    "choke_rate_sample_weight": 23.05884656500557,
    "comeback_rate": 0.6436883759452335,
    "comeback_rate_sample_weight": 26.741945526925853,
    "avg_volatility": 0.31879815237119796
  },
  "9572001": {
    "team_name": "Team Vision",
    "matches_with_curve": 278,
    "effective_n": 53.13728946940241,
    "avg_draft_stage_win_rate": 0.5154077921784799,
    "draft_favored_win_rate": 0.5540723419454069,
    "draft_favored_sample_weight": 27.604703879122706,
    "draft_underdog_win_rate": 0.5384659912628155,
    "draft_underdog_sample_weight": 25.532585590279716,
    "choke_rate": 0.45924835608906545,
    "choke_rate_sample_weight": 18.10570623855629,
    "comeback_rate": 0.6023368206336249,
    "comeback_rate_sample_weight": 15.458061324778136,
    "avg_volatility": 0.30272821152313323
  },
  "9823272": {
    "team_name": "Team Yandex",
    "matches_with_curve": 123,
    "effective_n": 54.77320910941938,
    "avg_draft_stage_win_rate": 0.546229780575543,
    "draft_favored_win_rate": 0.585100943200366,
    "draft_favored_sample_weight": 30.29189810776511,
    "draft_underdog_win_rate": 0.564883922021401,
    "draft_underdog_sample_weight": 24.481311001654255,
    "choke_rate": 0.42921342311832544,
    "choke_rate_sample_weight": 19.579429649621726,
    "comeback_rate": 0.5766102585127302,
    "comeback_rate_sample_weight": 14.38858822611455,
    "avg_volatility": 0.30427723355931907
  },
  "9964962": {
    "team_name": "GamerLegion",
    "matches_with_curve": 77,
    "effective_n": 36.11990692709155,
    "avg_draft_stage_win_rate": 0.5387203291840932,
    "draft_favored_win_rate": 0.3019059409309338,
    "draft_favored_sample_weight": 18.677827452566486,
    "draft_underdog_win_rate": 0.34099762469517236,
    "draft_underdog_sample_weight": 17.442079474525066,
    "choke_rate": 0.6278335994041521,
    "choke_rate_sample_weight": 15.151887237378244,
    "comeback_rate": 0.4322493216752165,
    "comeback_rate_sample_weight": 9.65092073886523,
    "avg_volatility": 0.3095461665162453
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "matches_with_curve": 132,
    "effective_n": 24.228246426966976,
    "avg_draft_stage_win_rate": 0.6108327223370705,
    "draft_favored_win_rate": 0.34981567822496346,
    "draft_favored_sample_weight": 14.025412186012707,
    "draft_underdog_win_rate": 0.360375928648872,
    "draft_underdog_sample_weight": 10.202834240954276,
    "choke_rate": 0.5750669160101693,
    "choke_rate_sample_weight": 11.546074572889971,
    "comeback_rate": 0.3944524037509783,
    "comeback_rate_sample_weight": 6.604301631677506,
    "avg_volatility": 0.3370921931915648
  },
  "10149530": {
    "team_name": "HULIGANI",
    "matches_with_curve": 34,
    "effective_n": 13.36723547703305,
    "avg_draft_stage_win_rate": 0.4519142085056718,
    "draft_favored_win_rate": 0.16964411203113702,
    "draft_favored_sample_weight": 5.873303258322201,
    "draft_underdog_win_rate": 0.3683579378754296,
    "draft_underdog_sample_weight": 7.493932218710851,
    "choke_rate": 0.8231065069611018,
    "choke_rate_sample_weight": 5.6326058060742525,
    "comeback_rate": 0.33171401907409387,
    "comeback_rate_sample_weight": 6.417052960254399,
    "avg_volatility": 0.41267606426705866
  },
  "10150413": {
    "team_name": "Iron Wing",
    "matches_with_curve": 259,
    "effective_n": 59.946340774346304,
    "avg_draft_stage_win_rate": 0.4833647062516308,
    "draft_favored_win_rate": 0.5006065450718017,
    "draft_favored_sample_weight": 26.655241329247595,
    "draft_underdog_win_rate": 0.559411380401471,
    "draft_underdog_sample_weight": 33.2910994450987,
    "choke_rate": 0.4872696844543073,
    "choke_rate_sample_weight": 20.11825523607033,
    "comeback_rate": 0.5287095872670883,
    "comeback_rate_sample_weight": 16.997859555280098,
    "avg_volatility": 0.2994646234952022
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "matches_with_curve": 189,
    "effective_n": 49.45148431278498,
    "avg_draft_stage_win_rate": 0.5056011836781501,
    "draft_favored_win_rate": 0.3297875777600654,
    "draft_favored_sample_weight": 23.610253889023568,
    "draft_underdog_win_rate": 0.4808310709722562,
    "draft_underdog_sample_weight": 25.84123042376139,
    "choke_rate": 0.6479925901525369,
    "choke_rate_sample_weight": 17.217310749529886,
    "comeback_rate": 0.508287577188363,
    "comeback_rate_sample_weight": 15.269059213197325,
    "avg_volatility": 0.3099069478273412
  }
};
