// AUTO-GENERATED by scripts/build-dataset.js - do not edit by hand.
// Regenerate with `npm run build-data` after the Python pipeline updates prediction/*.json.

export interface TeamStability {
  team_name: string;
  matches_with_curve: number;
  effective_n: number;
  avg_draft_stage_win_rate: number | null;
  draft_favored_win_rate: number | null;
  draft_favored_sample_weight: number;
  draft_underdog_win_rate: number | null;
  draft_underdog_sample_weight: number;
  choke_rate: number | null;
  choke_rate_sample_weight: number;
  comeback_rate: number | null;
  comeback_rate_sample_weight: number;
  avg_volatility: number | null;
}

export const stabilityMeta = {
  "choke_threshold": 0.7,
  "comeback_threshold": 0.3,
  "note": "avg_draft_stage_win_rate = decayed/tier-weighted average of predicted_win_rates[0] - Stratz's predicted win% immediately after the draft, before any in-game events - i.e. 'how good is this team's draft' on its own. draft_favored_win_rate/draft_underdog_win_rate = P(actual win | draft-stage prediction was >0.5 / <=0.5) - whether a good draft actually converts into a win and whether they can overcome a bad one; this is the draft-stage-specific analogue of choke_rate/comeback_rate below (0.5 threshold, single draft-stage value) as opposed to those (0.70/0.30 threshold, anywhere in the match). choke_rate = P(lose | was predicted >=70% favorite at some point in the match). comeback_rate = P(win | was predicted <=30% at some point). All rates are decayed/tier-weighted like the main rating. avg_volatility = average (peak-trough) swing in predicted win% across a team's games - higher means more rollercoaster games, lower means more control/dominant closeouts."
};

export const teamStability: Record<string, TeamStability> = {
  "2163": {
    "team_name": "Team Liquid",
    "matches_with_curve": 271,
    "effective_n": 69.43770285852312,
    "avg_draft_stage_win_rate": 0.48780139249553295,
    "draft_favored_win_rate": 0.5425756338735178,
    "draft_favored_sample_weight": 33.30203603721291,
    "draft_underdog_win_rate": 0.5372720214938104,
    "draft_underdog_sample_weight": 36.13566682131022,
    "choke_rate": 0.5244013899529014,
    "choke_rate_sample_weight": 19.498848050890025,
    "comeback_rate": 0.5118132219879441,
    "comeback_rate_sample_weight": 24.27011166009044,
    "avg_volatility": 0.3078810166757886
  },
  "726228": {
    "team_name": "Vici Gaming",
    "matches_with_curve": 59,
    "effective_n": 34.852042248762075,
    "avg_draft_stage_win_rate": 0.5046129785300171,
    "draft_favored_win_rate": 0.3374105915804776,
    "draft_favored_sample_weight": 19.262064574345086,
    "draft_underdog_win_rate": 0.5832202963498794,
    "draft_underdog_sample_weight": 15.589977674417003,
    "choke_rate": 0.720113811645775,
    "choke_rate_sample_weight": 12.14853571201652,
    "comeback_rate": 0.4440351017550559,
    "comeback_rate_sample_weight": 10.530699184098388,
    "avg_volatility": 0.307747592966734
  },
  "2586976": {
    "team_name": "OG",
    "matches_with_curve": 78,
    "effective_n": 37.96214901071343,
    "avg_draft_stage_win_rate": 0.5087237991280829,
    "draft_favored_win_rate": 0.3984363592371572,
    "draft_favored_sample_weight": 19.497339852387416,
    "draft_underdog_win_rate": 0.4379926818120291,
    "draft_underdog_sample_weight": 18.46480915832601,
    "choke_rate": 0.7069448225705446,
    "choke_rate_sample_weight": 10.119389447065885,
    "comeback_rate": 0.4467772929476393,
    "comeback_rate_sample_weight": 10.257915125725127,
    "avg_volatility": 0.30704829697405406
  },
  "5017210": {
    "team_name": "Team Resilience",
    "matches_with_curve": 9,
    "effective_n": 3.2921629940188595,
    "avg_draft_stage_win_rate": 0.5028865912840312,
    "draft_favored_win_rate": 0,
    "draft_favored_sample_weight": 1.2277286231930087,
    "draft_underdog_win_rate": 0,
    "draft_underdog_sample_weight": 2.0644343708258512,
    "choke_rate": 1,
    "choke_rate_sample_weight": 1.2277286231930087,
    "comeback_rate": 0,
    "comeback_rate_sample_weight": 1.032242458331536,
    "avg_volatility": 0.32932537378577187
  },
  "7119388": {
    "team_name": "Team Spirit",
    "matches_with_curve": 264,
    "effective_n": 63.255227862928486,
    "avg_draft_stage_win_rate": 0.5155241160685692,
    "draft_favored_win_rate": 0.5864897278427826,
    "draft_favored_sample_weight": 33.65706941670483,
    "draft_underdog_win_rate": 0.5605382079312607,
    "draft_underdog_sample_weight": 29.59815844622368,
    "choke_rate": 0.3249970075565458,
    "choke_rate_sample_weight": 22.32258718889219,
    "comeback_rate": 0.4809307010760047,
    "comeback_rate_sample_weight": 21.457386585569473,
    "avg_volatility": 0.31643068098618454
  },
  "8255888": {
    "team_name": "BoomBoys",
    "matches_with_curve": 264,
    "effective_n": 61.80797263620494,
    "avg_draft_stage_win_rate": 0.4871479255091898,
    "draft_favored_win_rate": 0.48034384959738996,
    "draft_favored_sample_weight": 29.307807320966287,
    "draft_underdog_win_rate": 0.5154920204120177,
    "draft_underdog_sample_weight": 32.500165315238625,
    "choke_rate": 0.5242624920863117,
    "choke_rate_sample_weight": 20.519351206793363,
    "comeback_rate": 0.6072965437716432,
    "comeback_rate_sample_weight": 19.694257995063438,
    "avg_volatility": 0.3073959348484592
  },
  "8261500": {
    "team_name": "Xtreme Gaming",
    "matches_with_curve": 134,
    "effective_n": 50.548684716860144,
    "avg_draft_stage_win_rate": 0.467719300578908,
    "draft_favored_win_rate": 0.4918220582438372,
    "draft_favored_sample_weight": 23.29136012631007,
    "draft_underdog_win_rate": 0.433880001805868,
    "draft_underdog_sample_weight": 27.25732459055007,
    "choke_rate": 0.4805039456481388,
    "choke_rate_sample_weight": 11.984208768592021,
    "comeback_rate": 0.31297942092795256,
    "comeback_rate_sample_weight": 18.893836719130206,
    "avg_volatility": 0.2931112557226594
  },
  "9247354": {
    "team_name": "Team Falcons",
    "matches_with_curve": 281,
    "effective_n": 74.55984080012811,
    "avg_draft_stage_win_rate": 0.47253815704588686,
    "draft_favored_win_rate": 0.5525795950000536,
    "draft_favored_sample_weight": 34.4590445241741,
    "draft_underdog_win_rate": 0.6368015167315458,
    "draft_underdog_sample_weight": 40.10079627595403,
    "choke_rate": 0.5183689303159231,
    "choke_rate_sample_weight": 24.443231782755394,
    "comeback_rate": 0.6157450626081833,
    "comeback_rate_sample_weight": 27.497910868158016,
    "avg_volatility": 0.3218717590077052
  },
  "9467224": {
    "team_name": "Aurora Gaming",
    "matches_with_curve": 139,
    "effective_n": 67.60101369095811,
    "avg_draft_stage_win_rate": 0.46602422827606477,
    "draft_favored_win_rate": 0.6208088590386969,
    "draft_favored_sample_weight": 30.175683835779143,
    "draft_underdog_win_rate": 0.5675566218388488,
    "draft_underdog_sample_weight": 37.425329855179,
    "choke_rate": 0.35042796480865923,
    "choke_rate_sample_weight": 23.180052025715778,
    "comeback_rate": 0.6438860556844798,
    "comeback_rate_sample_weight": 26.886225308989257,
    "avg_volatility": 0.3187990469440747
  },
  "9572001": {
    "team_name": "Team Vision",
    "matches_with_curve": 278,
    "effective_n": 53.37876381309469,
    "avg_draft_stage_win_rate": 0.5155298151578422,
    "draft_favored_win_rate": 0.5545529550270769,
    "draft_favored_sample_weight": 27.741008481931633,
    "draft_underdog_win_rate": 0.5382006026379372,
    "draft_underdog_sample_weight": 25.637755331163056,
    "choke_rate": 0.4589441266765081,
    "choke_rate_sample_weight": 18.201076966581763,
    "comeback_rate": 0.6021889468279698,
    "comeback_rate_sample_weight": 15.522102662766079,
    "avg_volatility": 0.3027348128479779
  },
  "9823272": {
    "team_name": "Team Yandex",
    "matches_with_curve": 123,
    "effective_n": 54.995283105382484,
    "avg_draft_stage_win_rate": 0.5463384116636496,
    "draft_favored_win_rate": 0.5852509877314075,
    "draft_favored_sample_weight": 30.419319033840793,
    "draft_underdog_win_rate": 0.5649654408126725,
    "draft_underdog_sample_weight": 24.575964071541662,
    "choke_rate": 0.4291283314441965,
    "choke_rate_sample_weight": 19.66837417379634,
    "comeback_rate": 0.5763600007589869,
    "comeback_rate_sample_weight": 14.452760672658352,
    "avg_volatility": 0.30440683777723127
  },
  "9964962": {
    "team_name": "GamerLegion",
    "matches_with_curve": 77,
    "effective_n": 36.28797546622826,
    "avg_draft_stage_win_rate": 0.5387259202407625,
    "draft_favored_win_rate": 0.3018755665990305,
    "draft_favored_sample_weight": 18.761315309400786,
    "draft_underdog_win_rate": 0.34060304090735244,
    "draft_underdog_sample_weight": 17.52666015682749,
    "choke_rate": 0.6280100363470875,
    "choke_rate_sample_weight": 15.225304086137724,
    "comeback_rate": 0.4318757063277209,
    "comeback_rate_sample_weight": 9.696567051512114,
    "avg_volatility": 0.3095861479172443
  },
  "10136357": {
    "team_name": "Nigma Galaxy",
    "matches_with_curve": 132,
    "effective_n": 24.36722589562675,
    "avg_draft_stage_win_rate": 0.6109080400351561,
    "draft_favored_win_rate": 0.3502321061255823,
    "draft_favored_sample_weight": 14.109669248780081,
    "draft_underdog_win_rate": 0.36046631347229546,
    "draft_underdog_sample_weight": 10.257556646846675,
    "choke_rate": 0.5745646432499016,
    "choke_rate_sample_weight": 11.615534767690574,
    "comeback_rate": 0.3946114613715727,
    "comeback_rate_sample_weight": 6.64551199470958,
    "avg_volatility": 0.3372031359028273
  },
  "10149530": {
    "team_name": "HULIGANI",
    "matches_with_curve": 34,
    "effective_n": 13.460766344290246,
    "avg_draft_stage_win_rate": 0.45185695226908457,
    "draft_favored_win_rate": 0.16961381935068753,
    "draft_favored_sample_weight": 5.913417014090965,
    "draft_underdog_win_rate": 0.3681395313726379,
    "draft_underdog_sample_weight": 7.547349330199283,
    "choke_rate": 0.8231945208806151,
    "choke_rate_sample_weight": 5.672885535951346,
    "comeback_rate": 0.3314666236183879,
    "comeback_rate_sample_weight": 6.46240773667144,
    "avg_volatility": 0.4127065407402824
  },
  "10150413": {
    "team_name": "Iron Wing",
    "matches_with_curve": 259,
    "effective_n": 60.18549327818615,
    "avg_draft_stage_win_rate": 0.48342360216100355,
    "draft_favored_win_rate": 0.5002471143883231,
    "draft_favored_sample_weight": 26.76373038247118,
    "draft_underdog_win_rate": 0.5593202336551498,
    "draft_underdog_sample_weight": 33.421762895714956,
    "choke_rate": 0.48764788096841705,
    "choke_rate_sample_weight": 20.20786590470687,
    "comeback_rate": 0.5286577450309312,
    "comeback_rate_sample_weight": 17.06072669124488,
    "avg_volatility": 0.2995399410753182
  },
  "10150538": {
    "team_name": "LGD Gaming",
    "matches_with_curve": 189,
    "effective_n": 49.64845324595223,
    "avg_draft_stage_win_rate": 0.5054533266015357,
    "draft_favored_win_rate": 0.329392866486094,
    "draft_favored_sample_weight": 23.700463177386244,
    "draft_underdog_win_rate": 0.4810214932348263,
    "draft_underdog_sample_weight": 25.947990068565993,
    "choke_rate": 0.6482779168793087,
    "choke_rate_sample_weight": 17.278534854977707,
    "comeback_rate": 0.5086410702587802,
    "comeback_rate_sample_weight": 15.339336068648489,
    "avg_volatility": 0.3099131604912397
  }
};
